In [1]:
import PyPDF2 
doc1 = open(r'C:\Users\AMRITHA R J\Downloads\omicron.pdf', 'rb') 
doc2 = open(r'C:\Users\AMRITHA R J\Downloads\t20.pdf', 'rb') 
doc3 = open(r'C:\Users\AMRITHA R J\Downloads\What is a Heart Attack.pdf', 'rb') 

In [2]:
pdf1 = PyPDF2.PdfFileReader(doc1)
pdf2 = PyPDF2.PdfFileReader(doc2) 
pdf3 = PyPDF2.PdfFileReader(doc3) 

Xref table not zero-indexed. ID numbers for objects will be corrected.


In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\AMRITHA R
[nltk_data]     J\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
m = pdf1.numPages
for i in range(m):
    page1 = pdf1.getPage(i)
    p = page1.extractText()
    
n = pdf2.numPages
for i in range(n):
    page2 = pdf2.getPage(i)
    q = page2.extractText()

o = pdf3.numPages
for i in range(o):
    page3 = pdf3.getPage(i)
    r = page3.extractText()
    
print(p)
print(q)
print(r)

8  Annex: Working  definitions  
 
 
Suspected reinfection case : Confirmed or probable COVID -19 case (following WHO case definition), with a history of a 
primary confirmed, or probable COVID -19 infection, with at least 90 days between the episodes.  
 
Probable reinfection case: Positive RT -qPCR testing results for both episodes or equivalent positive antigen tests fitting 
the WHO Case Definition with episodes occurring at least 90 days apart, based on the sampling date. OR - Genomic 
evidence for the second episode is available an d includes lineage that was not submitted to SARS -Cov-2 genomic 
databases at the time of first infection.  
 
Reinfection  confirmed by sequencing : Samples available for both primary and secondary episodes allowing for full 
genomic sequencing, whereby samples  must be shown to be phylogenetically distinct from one another. Evidence 
should be generated at clade/lineage, as defined by genomic classification of SARS -CoV-2 between the first and secon

In [5]:
docs = [p,q,r]
docs

["8  Annex: Working  definitions  \n \n \nSuspected reinfection case : Confirmed or probable COVID -19 case (following WHO case definition), with a history of a \nprimary confirmed, or probable COVID -19 infection, with at least 90 days between the episodes.  \n \nProbable reinfection case: Positive RT -qPCR testing results for both episodes or equivalent positive antigen tests fitting \nthe WHO Case Definition with episodes occurring at least 90 days apart, based on the sampling date. OR - Genomic \nevidence for the second episode is available an d includes lineage that was not submitted to SARS -Cov-2 genomic \ndatabases at the time of first infection.  \n \nReinfection  confirmed by sequencing : Samples available for both primary and secondary episodes allowing for full \ngenomic sequencing, whereby samples  must be shown to be phylogenetically distinct from one another. Evidence \nshould be generated at clade/lineage, as defined by genomic classification of SARS -CoV-2 between the 

In [6]:
unique_terms = {term for doc in docs for term in doc.split()}
unique_terms

{'(1-800-242-8721),',
 '(following',
 '(for',
 '(salt)',
 ',',
 '-',
 '-19',
 '-CoV-2',
 '-Cov-2',
 '-day',
 '-like',
 '-qPCR',
 '.',
 '.Do',
 '/',
 '1-800-AHA-USA1',
 '1/20',
 '14',
 '150',
 '18-24,',
 '2020',
 '501(c)(3)',
 '56m,',
 '7',
 '8',
 '90',
 ':',
 'Afghanistan,',
 'All',
 'America',
 'American',
 'An',
 'Annex:',
 'Apart',
 'Asian',
 'Association,',
 'Asymptomatic',
 'Attack?',
 'Authority',
 'Bangladesh,',
 'CAN',
 'COVID',
 'Call',
 'Case',
 'Cases',
 'Confirmed',
 'Connect',
 'Control',
 'Copyright',
 'CricketConclusions',
 'DS15225',
 'Definition',
 'Don’t',
 'Eat',
 'Emergency',
 'Even',
 'Evidence',
 'For',
 'Genomic',
 'Get',
 'Globalization',
 'HOW',
 'Heart',
 'Horizm',
 'How',
 'However,',
 'I',
 'IPL',
 'IPL,',
 'IPL.',
 'IPL’s',
 'If',
 'Improving',
 'Inc.,',
 'Indian',
 'Insight',
 'Is',
 'LEARN',
 'League',
 'Listing.',
 'MORE?',
 'MY',
 'Nepal',
 'Network',
 'North',
 'Nucleotide',
 'OR',
 'One',
 'Positive',
 'Premier',
 'Probable',
 'QUESTIONS:',
 'RNA',
 '

In [7]:
#Term document matrix

In [8]:
doc_term_matrix = {}

for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in docs:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

doc_term_matrix

{'write': [0, 0, 1],
 'you': [0, 1, 1],
 'my': [0, 0, 1],
 ',': [1, 1, 1],
 'attack.': [0, 0, 1],
 'minutes': [0, 0, 1],
 'markets': [0, 1, 0],
 'detection': [1, 0, 0],
 'saturated': [0, 0, 1],
 'case': [1, 0, 0],
 'marketplace.': [0, 1, 0],
 'that’s': [0, 0, 1],
 'are': [1, 1, 1],
 'fact': [1, 0, 1],
 '•': [1, 0, 1],
 'rehabilitation': [0, 0, 1],
 'was': [1, 1, 0],
 'aim': [0, 1, 0],
 'What': [0, 0, 1],
 'Cases': [1, 0, 0],
 'similar': [1, 0, 1],
 'how': [1, 1, 0],
 'doses': [1, 0, 0],
 'When': [0, 1, 0],
 'offers': [0, 1, 0],
 'Heart': [0, 0, 1],
 'sugars.': [0, 0, 1],
 'Single': [1, 0, 0],
 'lineage': [1, 0, 0],
 'League': [0, 1, 0],
 'audience,': [0, 1, 0],
 'popularity,': [0, 1, 0],
 'stroke.': [0, 0, 1],
 'which': [0, 1, 0],
 'nature': [1, 0, 0],
 'profile': [0, 1, 0],
 'also': [1, 1, 0],
 'success': [0, 1, 0],
 'provider': [0, 0, 1],
 '2020': [0, 0, 1],
 'proprietary': [1, 0, 0],
 'leagues': [0, 1, 0],
 'geographic': [0, 1, 0],
 'linages/clades.': [1, 0, 0],
 'understandably': [

In [9]:
import numpy as np
docs_array = np.array(docs, dtype='object')

v1 = np.array(doc_term_matrix['COVID'])    
v2 = np.array(doc_term_matrix['T20'])
v3 = np.array(doc_term_matrix['heart'])
print(v1)
print(v2)
print(v3)

[1 0 0]
[0 1 0]
[0 0 1]


In [10]:
v = v1 & v2 & v3
print(v)

[0 0 0]


In [11]:
v1 = np.array(doc_term_matrix['age'])    
v2 = np.array(doc_term_matrix['nationalities'])

print(v1)
print(v2)

[1 1 1]
[0 1 0]


In [12]:
v = v1 | v2
print(v)

[1 1 1]


In [13]:
#Inverted index

In [14]:
inverted_index = {}

for i, doc in enumerate(docs):
    for term in doc.split():
        if term in inverted_index:
            inverted_index[term].add(i)
        else: inverted_index[term] = {i}

inverted_index

{'8': {0},
 'Annex:': {0},
 'Working': {0},
 'definitions': {0},
 'Suspected': {0},
 'reinfection': {0},
 'case': {0},
 ':': {0},
 'Confirmed': {0},
 'or': {0, 2},
 'probable': {0},
 'COVID': {0},
 '-19': {0},
 '(following': {0},
 'WHO': {0},
 'definition),': {0},
 'with': {0, 1, 2},
 'a': {0, 1, 2},
 'history': {0},
 'of': {0, 1, 2},
 'primary': {0, 1},
 'confirmed,': {0},
 'infection,': {0},
 'at': {0, 1, 2},
 'least': {0, 2},
 '90': {0},
 'days': {0},
 'between': {0, 1},
 'the': {0, 1, 2},
 'episodes.': {0},
 'Probable': {0},
 'case:': {0},
 'Positive': {0},
 'RT': {0},
 '-qPCR': {0},
 'testing': {0},
 'results': {0},
 'for': {0, 1, 2},
 'both': {0},
 'episodes': {0},
 'equivalent': {0},
 'positive': {0},
 'antigen': {0},
 'tests': {0},
 'fitting': {0},
 'Case': {0},
 'Definition': {0},
 'occurring': {0},
 'apart,': {0},
 'based': {0},
 'on': {0, 1},
 'sampling': {0},
 'date.': {0},
 'OR': {0},
 '-': {0},
 'Genomic': {0},
 'evidence': {0},
 'second': {0},
 'episode': {0},
 'is': {0,

In [15]:
posting_list = inverted_index['time']
posting_list

{0, 2}